### ISSUE TITLE
error

### ISSUE THREAD

**Issue by seismoprocess** [xli2522/S-Transform#1]
Hii, i am trying to use stransfrom and inverse s transfrom using ur code
while i do 
out = sTransform(data, sample_rate=0.1, frange=[0,500])

I get error as follows
amp = np.zeros((int((Nfreq[1]-Nfreq[0])/frate)+1,length), dtype='c8')                    
numpy.core._exceptions.MemoryError: Unable to allocate 146. TiB for an array with shape (1000000001, 20000) and data type complex64

**Comment by xli2522** [comment]
How long is your data and what is the sampling rate? It looks like the problem is due to trying to allocate memory for a very large 2D array.

**Comment by seismoprocess** [comment]
i solved it by setting sample_rate =100, after that i get error

 line 55, in sTransform
    elevation=elevation))  
ValueError: operands could not be broadcast together with shapes (19999,) (20000,)

**Comment by xli2522** [comment]
Hi, I recreated the problem:
@seismoprocess 
`t = 10; rate = 100          # time 10s; sample rate 100 Hz
data = np.linspace(0, t, rate*t)         # time from 0 - 100s, 
table = sTransform(data, sample_rate=100, frange=[0,500])`

The upper frange value should be smaller than half of your sample_rate. This is called the Nyquist frequency. This program does handle values higher than the Nyquist frequency.
Try `sTransform(data, sample_rate=100, frange=[0,50])`.
